version: '3.8'

services:
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
    bookapi:
        image: bookapi
        restart: always
        ports:
            - 3000:3000
        links:
            - mongo
        environment:
            - DB_URL=mongodb://mongo:27017
            - DB_NAME=bookapi
